name: First Workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World"
      - name: Print goodbye
        run: echo "Good bye"
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 99
  seconds-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: Get Lost Message
        run: echo "Get Lost"
      - name: Say Hi Message
        run: echo "Hi, How are you"
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 15
       
        
    
